/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ActiveDecisionViewDto { 
    id?: number;
    type?: ActiveDecisionViewDto.TypeEnum;
    outcome?: ActiveDecisionViewDto.OutcomeEnum;
    notes?: string;
    decidedAt?: string;
    decidedByUsername?: string;
}
export namespace ActiveDecisionViewDto {
    export const TypeEnum = {
        Automatic: 'AUTOMATIC',
        Manual: 'MANUAL'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const OutcomeEnum = {
        Accept: 'ACCEPT',
        Reject: 'REJECT',
        Inconclusive: 'INCONCLUSIVE'
    } as const;
    export type OutcomeEnum = typeof OutcomeEnum[keyof typeof OutcomeEnum];
}


