/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Monument } from './monument';
import { Mark } from './mark';


export interface ActiveDecisionViewDto { 
    id?: number;
    type?: ActiveDecisionViewDto.TypeEnum;
    outcome?: ActiveDecisionViewDto.OutcomeEnum;
    confident?: boolean;
    detectedMark?: Mark;
    detectedMonument?: Monument;
    notes?: string;
    decidedAt?: string;
    decidedBy?: number;
}
export namespace ActiveDecisionViewDto {
    export const TypeEnum = {
        Automatic: 'AUTOMATIC',
        Manual: 'MANUAL'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const OutcomeEnum = {
        Accept: 'ACCEPT',
        Reject: 'REJECT',
        Inconclusive: 'INCONCLUSIVE'
    } as const;
    export type OutcomeEnum = typeof OutcomeEnum[keyof typeof OutcomeEnum];
}


