/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Geometry } from './geometry';
import { AuditActor } from './audit-actor';


export interface AdministrativeDivision { 
    createdAt?: string;
    createdBy?: AuditActor;
    lastModifiedAt?: string;
    modifiedBy?: AuditActor;
    id?: number;
    name?: string;
    adminLevel?: number;
    geometry?: Geometry;
}

