/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PhotoSize } from './photo-size';


export interface Animation { 
    file_id?: string;
    file_unique_id?: string;
    width?: number;
    height?: number;
    duration?: number;
    thumbnail?: PhotoSize;
    mime_type?: string;
    file_size?: number;
    file_name?: string;
}

