/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuditActor { 
    id?: number;
    type?: AuditActor.TypeEnum;
    identifier?: string;
}
export namespace AuditActor {
    export const TypeEnum = {
        User: 'USER',
        Service: 'SERVICE'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


