/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BookmarkDto { 
    id?: number;
    type?: BookmarkDto.TypeEnum;
    targetId?: number;
    content?: any | null;
}
export namespace BookmarkDto {
    export const TypeEnum = {
        Monument: 'MONUMENT',
        Mark: 'MARK',
        MarkOccurrence: 'MARK_OCCURRENCE',
        Guild: 'GUILD',
        Mason: 'MASON',
        User: 'USER',
        Proposal: 'PROPOSAL'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


