/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { MaybeInaccessibleMessage } from './maybe-inaccessible-message';


export interface CallbackQuery { 
    id?: string;
    from?: User;
    message?: MaybeInaccessibleMessage;
    inline_message_id?: string;
    data?: string;
    game_short_name?: string;
    chat_instance?: string;
}

