/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChatBoost { 
    boost_id?: string;
    add_date?: number;
    expiration_date?: number;
    source?: any | null;
}

