/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Chat } from './chat';


export interface ChatBoostRemoved { 
    chat?: Chat;
    boost_id?: string;
    remove_date?: number;
    source?: any | null;
}

