/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChatPhoto { 
    small_file_id?: string;
    small_file_unique_id?: string;
    big_file_id?: string;
    big_file_unique_id?: string;
}

