/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChatMember } from './chat-member';
import { User } from './user';
import { ChatInviteLink } from './chat-invite-link';
import { Chat } from './chat';


export interface ChatMemberUpdated { 
    chat?: Chat;
    from?: User;
    date?: number;
    old_chat_member?: ChatMember;
    new_chat_member?: ChatMember;
    invite_link?: ChatInviteLink;
    via_chat_folder_invite_link?: boolean;
}

