/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChatBoost } from './chat-boost';
import { Chat } from './chat';


export interface ChatBoostUpdated { 
    chat?: Chat;
    boost?: ChatBoost;
}

