/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { ChatInviteLink } from './chat-invite-link';
import { Chat } from './chat';


export interface ChatJoinRequest { 
    chat?: Chat;
    from?: User;
    date?: number;
    bio?: string;
    invite_link?: ChatInviteLink;
    user_chat_id?: number;
}

