/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChatPhoto } from './chat-photo';
import { Message } from './message';
import { ChatLocation } from './chat-location';
import { ChatPermissions } from './chat-permissions';


export interface Chat { 
    id?: number;
    type?: string;
    title?: string;
    first_name?: string;
    last_name?: string;
    username?: string;
    photo?: ChatPhoto;
    description?: string;
    invite_link?: string;
    pinned_message?: Message;
    sticker_set_name?: string;
    can_set_sticker_set?: boolean;
    permissions?: ChatPermissions;
    slow_mode_delay?: number;
    bio?: string;
    linked_chat_id?: number;
    location?: ChatLocation;
    message_auto_delete_time?: number;
    has_private_forwards?: boolean;
    has_protected_content?: boolean;
    join_to_send_messages?: boolean;
    join_by_request?: boolean;
    has_restricted_voice_and_video_messages?: boolean;
    is_forum?: boolean;
    active_usernames?: Array<string>;
    emoji_status_custom_emoji_id?: string;
    has_aggressive_anti_spam_enabled?: boolean;
    has_hidden_members?: boolean;
    emoji_status_expiration_date?: boolean;
    available_reactions?: Array<any>;
    accent_color_id?: number;
    background_custom_emoji_id?: string;
    profile_accent_color_id?: boolean;
    profile_background_custom_emoji_id?: string;
    has_visible_history?: boolean;
    unrestrict_boost_count?: number;
    custom_emoji_sticker_set_name?: boolean;
}

