/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Location } from './location';


export interface ChosenInlineQuery { 
    result_id?: string;
    from?: User;
    location?: Location;
    inline_message_id?: string;
    query?: string;
}

