/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConfirmationResponseDto { 
    status?: ConfirmationResponseDto.StatusEnum;
    message?: string;
    token?: string;
}
export namespace ConfirmationResponseDto {
    export const StatusEnum = {
        Success: 'SUCCESS',
        Error: 'ERROR',
        PasswordResetRequired: 'PASSWORD_RESET_REQUIRED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


