/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Contact details to be added
 */
export interface ContactDto { 
    value?: string;
    type?: ContactDto.TypeEnum;
}
export namespace ContactDto {
    export const TypeEnum = {
        Email: 'EMAIL',
        Telephone: 'TELEPHONE'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


