/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Contact { 
    phone_number?: string;
    first_name?: string;
    last_name?: string;
    user_id?: number;
    vcard?: string;
}

