/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface ContactRequest { 
    id?: number;
    name?: string;
    email?: string;
    subject?: string;
    message?: string;
    createdAt?: string;
    status?: ContactRequest.StatusEnum;
    submittedBy?: User;
}
export namespace ContactRequest {
    export const StatusEnum = {
        Pending: 'PENDING',
        InReview: 'IN_REVIEW',
        Resolved: 'RESOLVED',
        Archived: 'ARCHIVED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


