/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PassportFile } from './passport-file';


export interface EncryptedPassportElement { 
    type?: string;
    data?: string;
    phone_number?: string;
    email?: string;
    files?: Array<PassportFile>;
    front_side?: PassportFile;
    reverse_side?: PassportFile;
    selfie?: PassportFile;
    translation?: Array<PassportFile>;
    hash?: string;
}

