/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LinkPreviewOptions } from './link-preview-options';
import { Invoice } from './invoice';
import { Venue } from './venue';
import { Giveaway } from './giveaway';
import { Dice } from './dice';
import { Document } from './document';
import { Contact } from './contact';
import { VideoNote } from './video-note';
import { Sticker } from './sticker';
import { Game } from './game';
import { GiveawayWinners } from './giveaway-winners';
import { PhotoSize } from './photo-size';
import { Video } from './video';
import { Animation } from './animation';
import { Poll } from './poll';
import { Audio } from './audio';
import { Story } from './story';
import { Voice } from './voice';
import { Location } from './location';


export interface ExternalReplyInfo { 
    origin?: any | null;
    chat?: any | null;
    message_id?: number;
    link_preview_options?: LinkPreviewOptions;
    animation?: Animation;
    audio?: Audio;
    document?: Document;
    photo?: Array<PhotoSize>;
    sticker?: Sticker;
    story?: Story;
    video?: Video;
    video_note?: VideoNote;
    voice?: Voice;
    has_media_spoiler?: boolean;
    contact?: Contact;
    dice?: Dice;
    game?: Game;
    giveaway?: Giveaway;
    giveaway_winners?: GiveawayWinners;
    invoice?: Invoice;
    location?: Location;
    poll?: Poll;
    venue?: Venue;
}

