/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageEntity } from './message-entity';
import { PhotoSize } from './photo-size';
import { Animation } from './animation';


export interface Game { 
    title?: string;
    description?: string;
    photo?: Array<PhotoSize>;
    text?: string;
    text_entities?: Array<MessageEntity>;
    animation?: Animation;
}

