/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeometryFactory } from './geometry-factory';
import { Coordinate } from './coordinate';
import { PrecisionModel } from './precision-model';
import { Point } from './point';
import { Envelope } from './envelope';


export interface Geometry { 
    envelope?: Geometry;
    factory?: GeometryFactory;
    userData?: any | null;
    dimension?: number;
    length?: number;
    empty?: boolean;
    valid?: boolean;
    simple?: boolean;
    srid?: number;
    area?: number;
    boundaryDimension?: number;
    envelopeInternal?: Envelope;
    precisionModel?: PrecisionModel;
    centroid?: Point;
    geometryType?: string;
    numPoints?: number;
    boundary?: Geometry;
    coordinates?: Array<Coordinate>;
    numGeometries?: number;
    rectangle?: boolean;
    interiorPoint?: Point;
    coordinate?: Coordinate;
}

