/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PrecisionModel } from './precision-model';


export interface GeometryFactory { 
    precisionModel?: PrecisionModel;
    coordinateSequenceFactory?: any | null;
    srid?: number;
}

