/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Message } from './message';


export interface GiveawayCompleted { 
    winner_count?: number;
    unclaimed_prize_count?: number;
    giveaway_message?: Message;
}

