/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface GiveawayWinners { 
    chat?: any | null;
    giveaway_message_id?: number;
    winners_selection_date?: number;
    winner_count?: number;
    winners?: Array<User>;
    additional_chat_count?: number;
    premium_subscription_month_count?: number;
    unclaimed_prize_count?: number;
    only_new_members?: boolean;
    was_refunded?: boolean;
    prize_description?: string;
}

