/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Chat } from './chat';


export interface Giveaway { 
    chats?: Array<Chat>;
    winners_selection_date?: number;
    winner_count?: number;
    only_new_members?: boolean;
    has_public_winners?: boolean;
    prize_description?: string;
    country_codes?: Array<string>;
    premium_subscription_month_count?: number;
}

