/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WebAppInfo } from './web-app-info';
import { LoginUrl } from './login-url';


export interface InlineKeyboardButton { 
    text?: string;
    url?: string;
    callback_data?: string;
    callback_game?: any | null;
    switch_inline_query?: string;
    switch_inline_query_current_chat?: string;
    pay?: boolean;
    login_url?: LoginUrl;
    web_app?: WebAppInfo;
}

