/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineKeyboardButton } from './inline-keyboard-button';


export interface InlineKeyboardMarkup { 
    inline_keyboard?: Array<Array<InlineKeyboardButton>>;
}

