/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ButtonReply } from './button-reply';


export interface Interactive { 
    type?: string;
    button_reply?: ButtonReply;
}

