/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PhotoSize } from './photo-size';


export interface Invoice { 
    title?: string;
    description?: string;
    start_parameter?: string;
    currency?: string;
    total_amount?: number;
    photo?: PhotoSize;
}

