/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LinkedProviderDto { 
    provider?: LinkedProviderDto.ProviderEnum;
}
export namespace LinkedProviderDto {
    export const ProviderEnum = {
        Google: 'GOOGLE',
        Telegram: 'TELEGRAM'
    } as const;
    export type ProviderEnum = typeof ProviderEnum[keyof typeof ProviderEnum];
}


