/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoginUrl { 
    url?: string;
    forward_text?: string;
    bot_username?: string;
    request_write_access?: boolean;
}

