/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ManualDecisionRequest { 
    outcome?: ManualDecisionRequest.OutcomeEnum;
    notes?: string;
}
export namespace ManualDecisionRequest {
    export const OutcomeEnum = {
        Accept: 'ACCEPT',
        Reject: 'REJECT',
        Inconclusive: 'INCONCLUSIVE'
    } as const;
    export type OutcomeEnum = typeof OutcomeEnum[keyof typeof OutcomeEnum];
}


