/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MarkOccurrenceRequestDto { 
    markId: number;
    monumentId: number;
    coverId?: number;
    publishedAt?: string;
    active?: boolean;
}

