/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MarkDto } from './mark-dto';
import { MonumentMinDto } from './monument-min-dto';


export interface MarkOccurrenceDto { 
    id?: number;
    markId?: number;
    monumentId?: number;
    mark?: MarkDto;
    monument?: MonumentMinDto;
    coverId?: number;
    authorId?: number;
    authorName?: string;
    publishedAt?: string;
    active?: boolean;
}

