/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MediaFile } from './media-file';


export interface Mark { 
    createdAt?: string;
    createdById?: number;
    lastModifiedAt?: string;
    modifiedById?: number;
    id?: number;
    description?: string;
    cover?: MediaFile;
    embedding?: Array<number>;
}

