/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MediaFile } from './media-file';
import { AuditActor } from './audit-actor';


export interface Mark { 
    createdAt?: string;
    createdBy?: AuditActor;
    lastModifiedAt?: string;
    modifiedBy?: AuditActor;
    id?: number;
    description?: string;
    cover?: MediaFile;
    embedding?: Array<number>;
}

