/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MediaFileDto } from './media-file-dto';
import { ProposedMarkDto } from './proposed-mark-dto';
import { MarkDto } from './mark-dto';
import { ProposedMonumentDto } from './proposed-monument-dto';
import { MonumentResponseDto } from './monument-response-dto';


export interface MarkOccurrenceProposalDto { 
    id?: number;
    status?: MarkOccurrenceProposalDto.StatusEnum;
    originalMediaFile?: MediaFileDto;
    existingMonument?: MonumentResponseDto;
    proposedMonument?: ProposedMonumentDto;
    existingMark?: MarkDto;
    proposedMark?: ProposedMarkDto;
}
export namespace MarkOccurrenceProposalDto {
    export const StatusEnum = {
        InProgress: 'IN_PROGRESS',
        AwaitingMonumentInfo: 'AWAITING_MONUMENT_INFO',
        AwaitingMarkInfo: 'AWAITING_MARK_INFO',
        AwaitingMarkSelection: 'AWAITING_MARK_SELECTION',
        ReadyToSubmit: 'READY_TO_SUBMIT',
        Submitted: 'SUBMITTED',
        Approved: 'APPROVED',
        Rejected: 'REJECTED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


