/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MarkUpdateDto { 
    title?: string;
    description?: string;
    embedding?: Array<number>;
    coverId?: number;
}

