/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MediaFileDto } from './media-file-dto';
import { ProposedMarkDto } from './proposed-mark-dto';
import { MarkDto } from './mark-dto';
import { ProposedMonumentDto } from './proposed-monument-dto';
import { MonumentResponseDto } from './monument-response-dto';


export interface MarkOccurrenceProposalDto { 
    id?: number;
    priority?: number;
    originalMediaFile?: MediaFileDto;
    existingMonument?: MonumentResponseDto;
    proposedMonument?: ProposedMonumentDto;
    existingMark?: MarkDto;
    proposedMark?: ProposedMarkDto;
    isSubmitted?: boolean;
}

