/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MarkOccurrenceProposalListDto { 
    id?: number;
    coverId?: number;
    isSubmitted?: boolean;
    status?: MarkOccurrenceProposalListDto.StatusEnum;
    submittedAt?: string;
}
export namespace MarkOccurrenceProposalListDto {
    export const StatusEnum = {
        Submitted: 'SUBMITTED',
        UnderReview: 'UNDER_REVIEW',
        AutoAccepted: 'AUTO_ACCEPTED',
        AutoRejected: 'AUTO_REJECTED',
        ManuallyAccepted: 'MANUALLY_ACCEPTED',
        ManuallyRejected: 'MANUALLY_REJECTED',
        PendingMonumentCreation: 'PENDING_MONUMENT_CREATION'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


