/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MarkOccurrenceProposalCreateDto { 
    latitude: number;
    longitude: number;
    userNotes?: string;
    submissionSource: MarkOccurrenceProposalCreateDto.SubmissionSourceEnum;
    existingMonumentId?: number;
    existingMarkId?: number;
    photoId?: number;
}
export namespace MarkOccurrenceProposalCreateDto {
    export const SubmissionSourceEnum = {
        WebApp: 'WEB_APP',
        Whatsapp: 'WHATSAPP',
        Api: 'API',
        TelegramBot: 'TELEGRAM_BOT',
        Other: 'OTHER'
    } as const;
    export type SubmissionSourceEnum = typeof SubmissionSourceEnum[keyof typeof SubmissionSourceEnum];
}


