/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MediaFileDto } from './media-file-dto';


export interface MarkDto { 
    id?: number;
    title?: string;
    description?: string;
    embedding?: Array<number>;
    cover?: MediaFileDto;
}

