/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MarkDto } from './mark-dto';
import { MonumentResponseDto } from './monument-response-dto';


export interface MarkOccurrenceProposalDto { 
    id?: number;
    priority?: number;
    coverId?: number;
    existingMonument?: MonumentResponseDto;
    monumentName?: string;
    latitude?: number;
    longitude?: number;
    existingMark?: MarkDto;
    newMark?: boolean;
    userNotes?: string;
    submissionSource?: MarkOccurrenceProposalDto.SubmissionSourceEnum;
    isSubmitted?: boolean;
    status?: MarkOccurrenceProposalDto.StatusEnum;
}
export namespace MarkOccurrenceProposalDto {
    export const SubmissionSourceEnum = {
        WebApp: 'WEB_APP',
        StaffApp: 'STAFF_APP',
        Whatsapp: 'WHATSAPP',
        Api: 'API',
        TelegramBot: 'TELEGRAM_BOT',
        Other: 'OTHER'
    } as const;
    export type SubmissionSourceEnum = typeof SubmissionSourceEnum[keyof typeof SubmissionSourceEnum];
    export const StatusEnum = {
        Submitted: 'SUBMITTED',
        UnderReview: 'UNDER_REVIEW',
        AutoAccepted: 'AUTO_ACCEPTED',
        AutoRejected: 'AUTO_REJECTED',
        ManuallyAccepted: 'MANUALLY_ACCEPTED',
        ManuallyRejected: 'MANUALLY_REJECTED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


