/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MonumentDto } from './monument-dto';


export interface MarkOccurrenceDetailedDto { 
    id?: number;
    markId?: number;
    monument?: MonumentDto;
    coverId?: number;
    proposerId?: number;
    createdAt?: string;
}

