/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MarkDto { 
    id?: number;
    title?: string;
    description?: string;
    photoId?: number;
    vectorId?: number;
}

