/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDto } from './user-dto';
import { MarkDto } from './mark-dto';


export interface MarkOccurrenceDto { 
    id?: number;
    mark?: MarkDto;
    user?: UserDto;
    createdAt?: string;
}

