/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MaskPosition { 
    point?: string;
    x_shift?: number;
    y_shift?: number;
    scale?: number;
}

