/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MaybeInaccessibleMessage { 
    groupMessage?: boolean;
    userMessage?: boolean;
    superGroupMessage?: boolean;
    messageId?: number;
    chatId?: number;
    date?: number;
}

