/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MediaFile } from './media-file';


export interface MediaVariant { 
    id?: number;
    mediaFile?: MediaFile;
    type?: MediaVariant.TypeEnum;
    storagePath?: string;
    width?: number;
    height?: number;
    size?: number;
}
export namespace MediaVariant {
    export const TypeEnum = {
        Thumbnail: 'THUMBNAIL',
        Preview: 'PREVIEW',
        Optimized: 'OPTIMIZED'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


