/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MediaFileDto { 
    id?: number;
    filename?: string;
    originalFilename?: string;
    size?: number;
    status?: MediaFileDto.StatusEnum;
}
export namespace MediaFileDto {
    export const StatusEnum = {
        Uploaded: 'UPLOADED',
        Processing: 'PROCESSING',
        Ready: 'READY',
        Failed: 'FAILED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


