/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MediaFileDto { 
    id?: number;
    fileName?: string;
    originalFileName?: string;
    size?: number;
    storagePath?: string;
    uploadedAt?: string;
}

