/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MediaFile { 
    id?: number;
    filename?: string;
    originalFilename?: string;
    size?: number;
    storageProvider?: MediaFile.StorageProviderEnum;
    storagePath?: string;
    providerPublicId?: string;
    uploadedAt?: string;
    status?: MediaFile.StatusEnum;
}
export namespace MediaFile {
    export const StorageProviderEnum = {
        Local: 'LOCAL',
        Minio: 'MINIO',
        Azure: 'AZURE'
    } as const;
    export type StorageProviderEnum = typeof StorageProviderEnum[keyof typeof StorageProviderEnum];
    export const StatusEnum = {
        Uploaded: 'UPLOADED',
        Processing: 'PROCESSING',
        Ready: 'READY',
        Failed: 'FAILED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


