/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ForumTopicEdited } from './forum-topic-edited';
import { MessageAutoDeleteTimerChanged } from './message-auto-delete-timer-changed';
import { WriteAccessAllowed } from './write-access-allowed';
import { Invoice } from './invoice';
import { User } from './user';
import { UsersShared } from './users-shared';
import { ChatShared } from './chat-shared';
import { ForumTopicCreated } from './forum-topic-created';
import { Document } from './document';
import { VideoNote } from './video-note';
import { Sticker } from './sticker';
import { WebAppData } from './web-app-data';
import { GiveawayCompleted } from './giveaway-completed';
import { ProximityAlertTriggered } from './proximity-alert-triggered';
import { GiveawayWinners } from './giveaway-winners';
import { PhotoSize } from './photo-size';
import { Chat } from './chat';
import { SuccessfulPayment } from './successful-payment';
import { Story } from './story';
import { LinkPreviewOptions } from './link-preview-options';
import { ChatBoostAdded } from './chat-boost-added';
import { Venue } from './venue';
import { Giveaway } from './giveaway';
import { InlineKeyboardMarkup } from './inline-keyboard-markup';
import { Dice } from './dice';
import { Contact } from './contact';
import { VideoChatEnded } from './video-chat-ended';
import { VideoChatParticipantsInvited } from './video-chat-participants-invited';
import { MessageEntity } from './message-entity';
import { Game } from './game';
import { PassportData } from './passport-data';
import { MaybeInaccessibleMessage } from './maybe-inaccessible-message';
import { Video } from './video';
import { ExternalReplyInfo } from './external-reply-info';
import { UserShared } from './user-shared';
import { Animation } from './animation';
import { Poll } from './poll';
import { TextQuote } from './text-quote';
import { Audio } from './audio';
import { VideoChatScheduled } from './video-chat-scheduled';
import { Voice } from './voice';
import { Location } from './location';


export interface Message { 
    message_id?: number;
    message_thread_id?: number;
    from?: User;
    date?: number;
    chat?: Chat;
    forward_from?: User;
    forward_from_chat?: Chat;
    forward_date?: number;
    text?: string;
    entities?: Array<MessageEntity>;
    caption_entities?: Array<MessageEntity>;
    audio?: Audio;
    document?: Document;
    photo?: Array<PhotoSize>;
    sticker?: Sticker;
    video?: Video;
    contact?: Contact;
    location?: Location;
    venue?: Venue;
    animation?: Animation;
    pinned_message?: MaybeInaccessibleMessage;
    new_chat_members?: Array<User>;
    left_chat_member?: User;
    new_chat_title?: string;
    new_chat_photo?: Array<PhotoSize>;
    delete_chat_photo?: boolean;
    group_chat_created?: boolean;
    reply_to_message?: Message;
    voice?: Voice;
    caption?: string;
    supergroup_chat_created?: boolean;
    channel_chat_created?: boolean;
    migrate_to_chat_id?: number;
    migrate_from_chat_id?: number;
    edit_date?: number;
    game?: Game;
    forward_from_message_id?: number;
    invoice?: Invoice;
    successful_payment?: SuccessfulPayment;
    video_note?: VideoNote;
    author_signature?: string;
    forward_signature?: string;
    media_group_id?: string;
    connected_website?: string;
    passport_data?: PassportData;
    forward_sender_name?: string;
    poll?: Poll;
    reply_markup?: InlineKeyboardMarkup;
    dice?: Dice;
    via_bot?: User;
    sender_chat?: Chat;
    proximity_alert_triggered?: ProximityAlertTriggered;
    message_auto_delete_timer_changed?: MessageAutoDeleteTimerChanged;
    is_automatic_forward?: boolean;
    has_protected_content?: boolean;
    web_app_data?: WebAppData;
    video_chat_started?: any | null;
    video_chat_ended?: VideoChatEnded;
    video_chat_participants_invited?: VideoChatParticipantsInvited;
    video_chat_scheduled?: VideoChatScheduled;
    is_topic_message?: boolean;
    forum_topic_created?: ForumTopicCreated;
    forum_topic_closed?: any | null;
    forum_topic_reopened?: any | null;
    forum_topic_edited?: ForumTopicEdited;
    general_forum_topic_hidden?: any | null;
    general_forum_topic_unhidden?: any | null;
    write_access_allowed?: WriteAccessAllowed;
    has_media_spoiler?: boolean;
    user_shared?: UserShared;
    chat_shared?: ChatShared;
    story?: Story;
    external_reply?: ExternalReplyInfo;
    forward_origin?: any | null;
    link_preview_options?: LinkPreviewOptions;
    quote?: TextQuote;
    users_shared?: UsersShared;
    giveaway_created?: any | null;
    giveaway?: Giveaway;
    giveaway_winners?: GiveawayWinners;
    giveaway_completed?: GiveawayCompleted;
    reply_to_story?: Story;
    boost_added?: ChatBoostAdded;
    sender_boost_count?: number;
}

