/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Chat } from './chat';


export interface MessageReactionUpdated { 
    chat?: Chat;
    message_id?: number;
    user?: User;
    actor_chat?: Chat;
    date?: number;
    old_reaction?: Array<any>;
    new_reaction?: Array<any>;
}

