/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Interactive } from './interactive';
import { Text } from './text';
import { Image } from './image';
import { Location } from './location';


export interface Message { 
    from?: string;
    id?: string;
    timestamp?: string;
    type?: string;
    text?: Text;
    image?: Image;
    location?: Location;
    interactive?: Interactive;
}

