/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReactionCount } from './reaction-count';
import { Chat } from './chat';


export interface MessageReactionCountUpdated { 
    chat?: Chat;
    message_id?: number;
    date?: number;
    reactions?: Array<ReactionCount>;
}

