/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface MessageEntity { 
    type?: string;
    offset?: number;
    length?: number;
    url?: string;
    user?: User;
    language?: string;
    custom_emoji_id?: string;
}

