/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MonumentRequestDto { 
    name: string;
    description?: string;
    protectionTitle?: string;
    website?: string;
    latitude: number;
    longitude: number;
    street?: string;
    houseNumber?: string;
    parishId?: number;
    municipalityId?: number;
    districtId?: number;
    coverId?: number;
    active?: boolean;
}

