/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MonumentListDto { 
    id?: number;
    name?: string;
    parishId?: number;
    municipalityId?: number;
    districtId?: number;
    coverId?: number;
}

