/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdministrativeDivisionDto } from './administrative-division-dto';


export interface MonumentDto { 
    id?: number;
    name?: string;
    description?: string;
    latitude?: number;
    longitude?: number;
    street?: string;
    houseNumber?: string;
    parish?: AdministrativeDivisionDto;
    municipality?: AdministrativeDivisionDto;
    district?: AdministrativeDivisionDto;
    coverId?: number;
    protectionTitle?: string;
    website?: string;
    parishId?: number;
    municipalityId?: number;
    districtId?: number;
    active?: boolean;
    createdAt?: string;
    lastModifiedAt?: string;
}

