/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdministrativeDivisionDto } from './administrative-division-dto';


export interface MonumentResponseDto { 
    id?: number;
    name?: string;
    description?: string;
    protectionTitle?: string;
    website?: string;
    latitude?: number;
    longitude?: number;
    street?: string;
    houseNumber?: string;
    parish?: AdministrativeDivisionDto;
    municipality?: AdministrativeDivisionDto;
    district?: AdministrativeDivisionDto;
    coverId?: number;
    createdAt?: string;
    lastModifiedAt?: string;
}

