/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MediaFile } from './media-file';
import { AuditActor } from './audit-actor';


export interface Monument { 
    createdAt?: string;
    createdBy?: AuditActor;
    lastModifiedAt?: string;
    modifiedBy?: AuditActor;
    id?: number;
    name?: string;
    description?: string;
    latitude?: number;
    longitude?: number;
    website?: string;
    protectionTitle?: string;
    address?: string;
    city?: string;
    cover?: MediaFile;
}

