/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShippingAddress } from './shipping-address';


export interface OrderInfo { 
    name?: string;
    phone_number?: string;
    email?: string;
    shipping_address?: ShippingAddress;
}

