/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageableObject } from './pageable-object';
import { MarkOccurrenceDto } from './mark-occurrence-dto';
import { SortObject } from './sort-object';


export interface PageMarkOccurrenceDto { 
    totalPages?: number;
    totalElements?: number;
    pageable?: PageableObject;
    numberOfElements?: number;
    size?: number;
    content?: Array<MarkOccurrenceDto>;
    number?: number;
    sort?: SortObject;
    first?: boolean;
    last?: boolean;
    empty?: boolean;
}

