/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SortObject } from './sort-object';


export interface PageableObject { 
    unpaged?: boolean;
    pageNumber?: number;
    paged?: boolean;
    pageSize?: number;
    offset?: number;
    sort?: SortObject;
}

