/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PassportFile { 
    file_id?: string;
    file_unique_id?: string;
    file_size?: number;
    file_date?: number;
}

