/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EncryptedCredentials } from './encrypted-credentials';
import { EncryptedPassportElement } from './encrypted-passport-element';


export interface PassportData { 
    data?: Array<EncryptedPassportElement>;
    credentials?: EncryptedCredentials;
}

