/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PhotoSize { 
    file_id?: string;
    file_unique_id?: string;
    width?: number;
    height?: number;
    file_size?: number;
    file_path?: string;
}

