/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoordinateSequence } from './coordinate-sequence';
import { GeometryFactory } from './geometry-factory';
import { Coordinate } from './coordinate';
import { PrecisionModel } from './precision-model';
import { Envelope } from './envelope';


export interface Point { 
    envelope?: any | null;
    factory?: GeometryFactory;
    userData?: any | null;
    coordinates?: Array<Coordinate>;
    dimension?: number;
    empty?: boolean;
    simple?: boolean;
    boundaryDimension?: number;
    geometryType?: string;
    numPoints?: number;
    boundary?: any | null;
    coordinate?: Coordinate;
    x?: number;
    y?: number;
    coordinateSequence?: CoordinateSequence;
    length?: number;
    valid?: boolean;
    srid?: number;
    area?: number;
    envelopeInternal?: Envelope;
    precisionModel?: PrecisionModel;
    centroid?: any | null;
    numGeometries?: number;
    rectangle?: boolean;
    interiorPoint?: any | null;
}

