/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageEntity } from './message-entity';
import { PollOption } from './poll-option';


export interface Poll { 
    id?: string;
    question?: string;
    options?: Array<PollOption>;
    total_voter_count?: number;
    is_closed?: boolean;
    is_anonymous?: boolean;
    type?: string;
    allows_multiple_answers?: boolean;
    correct_option_id?: number;
    open_period?: number;
    close_date?: number;
    explanation?: string;
    explanation_entities?: Array<MessageEntity>;
}

