/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Chat } from './chat';


export interface PollAnswer { 
    poll_id?: string;
    user?: User;
    option_ids?: Array<number>;
    voter_chat?: Chat;
}

