/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { OrderInfo } from './order-info';


export interface PreCheckoutQuery { 
    id?: string;
    from?: User;
    currency?: string;
    total_amount?: number;
    invoice_payload?: string;
    shipping_option_id?: string;
    order_info?: OrderInfo;
}

