/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Updated profile information
 */
export interface ProfileUpdateRequestDto { 
    firstName: string;
    lastName: string;
    photoId?: number;
}

