/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProposalModeratorListDto { 
    id?: number;
    status?: ProposalModeratorListDto.StatusEnum;
    priority?: number;
    submissionSource?: ProposalModeratorListDto.SubmissionSourceEnum;
    submittedAt?: string;
    monumentName?: string;
}
export namespace ProposalModeratorListDto {
    export const StatusEnum = {
        Submitted: 'SUBMITTED',
        UnderReview: 'UNDER_REVIEW',
        AutoAccepted: 'AUTO_ACCEPTED',
        AutoRejected: 'AUTO_REJECTED',
        ManuallyAccepted: 'MANUALLY_ACCEPTED',
        ManuallyRejected: 'MANUALLY_REJECTED',
        PendingMonumentCreation: 'PENDING_MONUMENT_CREATION'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
    export const SubmissionSourceEnum = {
        WebApp: 'WEB_APP',
        Whatsapp: 'WHATSAPP',
        Api: 'API',
        TelegramBot: 'TELEGRAM_BOT',
        Other: 'OTHER'
    } as const;
    export type SubmissionSourceEnum = typeof SubmissionSourceEnum[keyof typeof SubmissionSourceEnum];
}


