/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MediaFileDto } from './media-file-dto';
import { UserDto } from './user-dto';
import { MarkDto } from './mark-dto';
import { MonumentDto } from './monument-dto';


export interface ProposalWithRelationsDto { 
    id?: number;
    existingMark?: MarkDto;
    existingMonument?: MonumentDto;
    originalMediaFile?: MediaFileDto;
    userNotes?: string;
    latitude?: number;
    longitude?: number;
    submissionSource?: ProposalWithRelationsDto.SubmissionSourceEnum;
    priority?: number;
    credibilityScore?: number;
    submitted?: boolean;
    submittedBy?: UserDto;
    submittedAt?: string;
    newMark?: boolean;
    status?: ProposalWithRelationsDto.StatusEnum;
}
export namespace ProposalWithRelationsDto {
    export const SubmissionSourceEnum = {
        WebApp: 'WEB_APP',
        Whatsapp: 'WHATSAPP',
        Api: 'API',
        TelegramBot: 'TELEGRAM_BOT',
        Other: 'OTHER'
    } as const;
    export type SubmissionSourceEnum = typeof SubmissionSourceEnum[keyof typeof SubmissionSourceEnum];
    export const StatusEnum = {
        Submitted: 'SUBMITTED',
        UnderReview: 'UNDER_REVIEW',
        AutoAccepted: 'AUTO_ACCEPTED',
        AutoRejected: 'AUTO_REJECTED',
        ManuallyAccepted: 'MANUALLY_ACCEPTED',
        ManuallyRejected: 'MANUALLY_REJECTED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


