/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MarkOccurrenceProposalDto } from './mark-occurrence-proposal-dto';


export interface ProposalStateDto { 
    proposal?: MarkOccurrenceProposalDto;
    nextAction?: ProposalStateDto.NextActionEnum;
    message?: string;
}
export namespace ProposalStateDto {
    export const NextActionEnum = {
        InProgress: 'IN_PROGRESS',
        AwaitingAuthentication: 'AWAITING_AUTHENTICATION',
        AwaitingMonumentInfo: 'AWAITING_MONUMENT_INFO',
        AwaitingMonumentName: 'AWAITING_MONUMENT_NAME',
        AwaitingMarkInfo: 'AWAITING_MARK_INFO',
        AwaitingMarkSelection: 'AWAITING_MARK_SELECTION',
        AwaitingMonumentSelection: 'AWAITING_MONUMENT_SELECTION',
        AwaitingMonumentVerification: 'AWAITING_MONUMENT_VERIFICATION',
        AwaitingNotes: 'AWAITING_NOTES',
        ReadyToSubmit: 'READY_TO_SUBMIT',
        Submitted: 'SUBMITTED',
        Approved: 'APPROVED',
        Rejected: 'REJECTED'
    } as const;
    export type NextActionEnum = typeof NextActionEnum[keyof typeof NextActionEnum];
}


