/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProposalSummaryDto { 
    id?: number;
    title?: string;
    type?: string;
    photoId?: number;
    status?: ProposalSummaryDto.StatusEnum;
    submittedAt?: string;
}
export namespace ProposalSummaryDto {
    export const StatusEnum = {
        Submitted: 'SUBMITTED',
        UnderReview: 'UNDER_REVIEW',
        AutoAccepted: 'AUTO_ACCEPTED',
        AutoRejected: 'AUTO_REJECTED',
        ManuallyAccepted: 'MANUALLY_ACCEPTED',
        ManuallyRejected: 'MANUALLY_REJECTED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


