/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MediaFileDto } from './media-file-dto';


export interface ProposedMarkDto { 
    id?: number;
    description?: string;
    mediaFile?: MediaFileDto;
}

