/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterRequestDto { 
    firstName?: string;
    lastName?: string;
    email?: string;
    telephone?: string;
    password?: string;
    role?: RegisterRequestDto.RoleEnum;
}
export namespace RegisterRequestDto {
    export const RoleEnum = {
        User: 'USER',
        Contributor: 'CONTRIBUTOR',
        Reviewer: 'REVIEWER',
        Moderator: 'MODERATOR',
        Admin: 'ADMIN'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


