/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReportResponseDto { 
    id?: number;
    userId?: number;
    targetId?: number;
    targetType?: ReportResponseDto.TargetTypeEnum;
    reason?: ReportResponseDto.ReasonEnum;
    description?: string;
    status?: ReportResponseDto.StatusEnum;
    createdAt?: string;
}
export namespace ReportResponseDto {
    export const TargetTypeEnum = {
        Monument: 'MONUMENT',
        Mark: 'MARK',
        MarkOccurrence: 'MARK_OCCURRENCE',
        Guild: 'GUILD',
        Mason: 'MASON',
        User: 'USER',
        Proposal: 'PROPOSAL'
    } as const;
    export type TargetTypeEnum = typeof TargetTypeEnum[keyof typeof TargetTypeEnum];
    export const ReasonEnum = {
        IncorrectInformation: 'INCORRECT_INFORMATION',
        WrongLocation: 'WRONG_LOCATION',
        Duplicate: 'DUPLICATE',
        DamagedMark: 'DAMAGED_MARK',
        InappropriateContent: 'INAPPROPRIATE_CONTENT',
        Other: 'OTHER'
    } as const;
    export type ReasonEnum = typeof ReasonEnum[keyof typeof ReasonEnum];
    export const StatusEnum = {
        Pending: 'PENDING',
        UnderReview: 'UNDER_REVIEW',
        Resolved: 'RESOLVED',
        Rejected: 'REJECTED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


