/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReportRequestDto { 
    targetId: number;
    targetType: ReportRequestDto.TargetTypeEnum;
    reason: ReportRequestDto.ReasonEnum;
    description?: string;
}
export namespace ReportRequestDto {
    export const TargetTypeEnum = {
        Monument: 'MONUMENT',
        Mark: 'MARK',
        MarkOccurrence: 'MARK_OCCURRENCE',
        Guild: 'GUILD',
        Mason: 'MASON',
        User: 'USER',
        Proposal: 'PROPOSAL'
    } as const;
    export type TargetTypeEnum = typeof TargetTypeEnum[keyof typeof TargetTypeEnum];
    export const ReasonEnum = {
        IncorrectInformation: 'INCORRECT_INFORMATION',
        WrongLocation: 'WRONG_LOCATION',
        Duplicate: 'DUPLICATE',
        DamagedMark: 'DAMAGED_MARK',
        InappropriateContent: 'INAPPROPRIATE_CONTENT',
        Other: 'OTHER'
    } as const;
    export type ReasonEnum = typeof ReasonEnum[keyof typeof ReasonEnum];
}


