/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SetTfaMethodRequestDto { 
    tfaMethod: SetTfaMethodRequestDto.TfaMethodEnum;
}
export namespace SetTfaMethodRequestDto {
    export const TfaMethodEnum = {
        None: 'NONE',
        Totp: 'TOTP',
        Sms: 'SMS',
        Email: 'EMAIL'
    } as const;
    export type TfaMethodEnum = typeof TfaMethodEnum[keyof typeof TfaMethodEnum];
}


