/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { ShippingAddress } from './shipping-address';


export interface ShippingQuery { 
    id?: string;
    from?: User;
    invoice_payload?: string;
    shipping_address?: ShippingAddress;
}

