/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ShippingAddress { 
    country_code?: string;
    state?: string;
    city?: string;
    street_line1?: string;
    street_line2?: string;
    post_code?: string;
}

