/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PhotoSize } from './photo-size';
import { MaskPosition } from './mask-position';


export interface Sticker { 
    file_id?: string;
    file_unique_id?: string;
    type?: string;
    width?: number;
    height?: number;
    thumbnail?: PhotoSize;
    file_size?: number;
    emoji?: string;
    set_name?: string;
    mask_position?: MaskPosition;
    is_animated?: boolean;
    is_video?: boolean;
    premium_animation?: any;
    custom_emoji_id?: string;
    needs_repainting?: boolean;
}

