/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderInfo } from './order-info';


export interface SuccessfulPayment { 
    currency?: string;
    total_amount?: number;
    invoice_payload?: string;
    shipping_option_id?: string;
    order_info?: OrderInfo;
    telegram_payment_charge_id?: string;
    provider_payment_charge_id?: string;
}

