/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageEntity } from './message-entity';


export interface TextQuote { 
    text?: string;
    entities?: Array<MessageEntity>;
    position?: number;
    is_manual?: boolean;
}

