/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CallbackQuery } from './callback-query';
import { MessageReactionUpdated } from './message-reaction-updated';
import { Message } from './message';
import { ShippingQuery } from './shipping-query';
import { ChosenInlineQuery } from './chosen-inline-query';
import { MessageReactionCountUpdated } from './message-reaction-count-updated';
import { PreCheckoutQuery } from './pre-checkout-query';
import { ChatBoostRemoved } from './chat-boost-removed';
import { ChatMemberUpdated } from './chat-member-updated';
import { PollAnswer } from './poll-answer';
import { ChatJoinRequest } from './chat-join-request';
import { Poll } from './poll';
import { ChatBoostUpdated } from './chat-boost-updated';
import { InlineQuery } from './inline-query';


export interface Update { 
    update_id?: number;
    message?: Message;
    inline_query?: InlineQuery;
    chosen_inline_result?: ChosenInlineQuery;
    callback_query?: CallbackQuery;
    edited_message?: Message;
    channel_post?: Message;
    edited_channel_post?: Message;
    shipping_query?: ShippingQuery;
    pre_checkout_query?: PreCheckoutQuery;
    poll?: Poll;
    poll_answer?: PollAnswer;
    my_chat_member?: ChatMemberUpdated;
    chat_member?: ChatMemberUpdated;
    chat_join_request?: ChatJoinRequest;
    message_reaction?: MessageReactionUpdated;
    message_reaction_count?: MessageReactionCountUpdated;
    chat_boost?: ChatBoostUpdated;
    removed_chat_boost?: ChatBoostRemoved;
}

