/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDto { 
    id?: number;
    firstName?: string;
    lastName?: string;
    username?: string;
    role?: UserDto.RoleEnum;
    createdAt?: string;
    tfaMethod?: UserDto.TfaMethodEnum;
    accountLocked?: boolean;
    enabled?: boolean;
    photoId?: number;
}
export namespace UserDto {
    export const RoleEnum = {
        User: 'USER',
        Reviewer: 'REVIEWER',
        Moderator: 'MODERATOR',
        Admin: 'ADMIN'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
    export const TfaMethodEnum = {
        None: 'NONE',
        Totp: 'TOTP',
        Sms: 'SMS',
        Email: 'EMAIL'
    } as const;
    export type TfaMethodEnum = typeof TfaMethodEnum[keyof typeof TfaMethodEnum];
}


