/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserContactDto { 
    id?: number;
    value?: string;
    type?: UserContactDto.TypeEnum;
    isPrimary?: boolean;
    isVerified?: boolean;
}
export namespace UserContactDto {
    export const TypeEnum = {
        Email: 'EMAIL',
        Telephone: 'TELEPHONE'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


