/**
 * StoneMark API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Message } from './message';
import { Metadata } from './metadata';
import { Contact } from './contact';


export interface Value { 
    metadata?: Metadata;
    contacts?: Array<Contact>;
    messages?: Array<Message>;
    messaging_product?: string;
}

